-- 修复调解相关表的自增ID问题 - 版本2
-- 请在数据库管理工具中以root用户执行

-- 方法1: 直接修改列属性
ALTER TABLE mediation_archives MODIFY id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE mediation_applications MODIFY id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE mediation_applicants MODIFY id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE mediation_respondents MODIFY id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE mediation_records MODIFY id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE mediation_agreements MODIFY id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE archive_attachments MODIFY id INT NOT NULL AUTO_INCREMENT;

-- 如果方法1失败，尝试方法2: 先删除主键再重新添加
-- ALTER TABLE mediation_archives DROP PRIMARY KEY, MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
-- ALTER TABLE mediation_applications DROP PRIMARY KEY, MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
-- ALTER TABLE mediation_applicants DROP PRIMARY KEY, MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
-- ALTER TABLE mediation_respondents DROP PRIMARY KEY, MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
-- ALTER TABLE mediation_records DROP PRIMARY KEY, MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
-- ALTER TABLE mediation_agreements DROP PRIMARY KEY, MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
-- ALTER TABLE archive_attachments DROP PRIMARY KEY, MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
